### ISSUE TITLE
GRIG 내 6기 기수 표기 오류

### ISSUE THREAD

**Issue by mingyeongmo** [GRI-G/GRIG-API#8]
<img width="1248" alt="스크린샷 2022-04-29 오후 2 41 17" src="https://user-images.githubusercontent.com/69895445/165890351-f2089817-81a6-4311-8763-ea4e279ef084.png">

--- 

64위의 프로필에서 기수가 올바르지 않게 표기되는 문제가 있습니다.

**Comment by sunrabbit123** [comment]
수정했습니다~
